install.packages('rjson')
install.packages('jsonlite')
library('rjson')
library('jsonlite')

Data <- fromJSON("Streaming_History_Audio_2019-2020_0.json")
Data2 <- fromJSON("Streaming_History_Audio_2020-2021_1.json")
Data3 <- fromJSON("Streaming_History_Audio_2021-2022_2.json")
Data4 <- fromJSON("Streaming_History_Audio_2022_3.json")
Data5 <- fromJSON("Streaming_History_Audio_2022_4.json")
Data6 <- fromJSON("Streaming_History_Audio_2022_5.json")
Data7 <- fromJSON("Streaming_History_Audio_2022_6.json")
Data8 <- fromJSON("Streaming_History_Audio_2022-2023_7.json")
Data9 <- fromJSON("Streaming_History_Audio_2023_8.json")
Data10 <- fromJSON("Streaming_History_Audio_2023_9.json")
Data11 <- fromJSON("Streaming_History_Audio_2023_10.json")
Data12 <- fromJSON("Streaming_History_Audio_2023_11.json")
Data13 <- fromJSON("Streaming_History_Audio_2023-2024_12.json")
Data14 <- fromJSON("Streaming_History_Audio_2024_13.json")
Data15 <- fromJSON("Streaming_History_Audio_2024_14.json")

MainData <- rbind(Data, Data2)
MainData <- rbind(MainData, Data3)
MainData <- rbind(MainData, Data4)
MainData <- rbind(MainData, Data5)
MainData <- rbind(MainData, Data6)
MainData <- rbind(MainData, Data7)
MainData <- rbind(MainData, Data8)
MainData <- rbind(MainData, Data9)
MainData <- rbind(MainData, Data10)
MainData <- rbind(MainData, Data11)
MainData <- rbind(MainData, Data12)
MainData <- rbind(MainData, Data13)
MainData <- rbind(MainData, Data14)
MainData <- rbind(MainData, Data15)

ListeningData <- select(MainData, -X, -platform, -conn_country, -episode_name, -episode_show_name, -spotify_episode_uri, -incognito_mode)
ListeningData <- select(ListeningData, -username, -ip_addr_decrypted, -user_agent_decrypted, -offline_timestamp, -skipped)
write.csv(ListeningData, file="Project2CleanedDataset.csv")



